version: '3'

services:
  next-app:
    build:
      context: ./
      dockerfile: prod.Dockerfile
      args:
        NEXT_PUBLIC_ICESERVER: ${NEXT_PUBLIC_ICESERVER:-local}
        NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL:-https://192.168.2.5:5443}
        # Set NODE_TLS_REJECT_UNAUTHORIZED to 0 to allow self-signed certificates in production (only for local network testing, not recommended for production use)
        NODE_TLS_REJECT_UNAUTHORIZED: '0'
    restart: always
    # ports:
    #   - 3000:3000
    networks:
      - domex

  domex-nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - domex

networks:
  domex:
    external: true
